language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
- 3.7
- 3.8
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- python setup.py develop
script:
- nosetests
env:
  global:
    secure: OEf+n4gbaDOfj7kqVjA3sjkIYtIsfEv6K2/5RejYxMoaAHEOR5r79HatWa4D2gmJxNZa+Biro6aep17opbBhMY3FAB/RK9dqW966YMpiOIgI5CF6lQeleOik61ByFYgJgp6S4pNS0wD9hOSN42sK0AX4f67m7KlsTAyFkV7ZgQo=
